import type { Metadata } from 'next';
import './globals.css';
import Main from './components/main';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout() {
  return (
    <html lang="en">
      <body>
        <Main />
      </body>
    </html>
  );
}
